## Import NumPy

In [1]:
import numpy as np

## Creating Arrays

###### Create a 1-Dimesnional numpy array

In [2]:
score=np.array([70,63,81,58,76])
print(score)

[70 63 81 58 76]


###### Create a 2*5 2-Dimesnional numpy array

In [3]:
score_height=np.array([([70,63,81,58,76]),(5.1,4.5,6.0,5.3,5.5)])
print(score_height)

[[70.  63.  81.  58.  76. ]
 [ 5.1  4.5  6.   5.3  5.5]]


###### Create a 4*5 2-Dimesnional 0s numpy array

In [4]:
zero=np.zeros((4,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###### Create a 4*5 2-Dimesnional 1s numpy array

In [5]:
one=np.ones((4,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###### Create a 5*5 identity matrix

In [6]:
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Inspecting Arrays

###### Find the number of elements in an array

In [7]:
print(score_height)
print(score_height.size)

[[70.  63.  81.  58.  76. ]
 [ 5.1  4.5  6.   5.3  5.5]]
10


###### Find the dimensions of an array

In [8]:
print(score_height.shape)

(2, 5)


###### Find the data type of elements in the array

In [9]:
print(score_height.dtype)

float64


###### Convert array to Python list

In [10]:
print("NumPy array : \n ",score_height)
print("\nPython list : \n",score_height.tolist())

NumPy array : 
  [[70.  63.  81.  58.  76. ]
 [ 5.1  4.5  6.   5.3  5.5]]

Python list : 
 [[70.0, 63.0, 81.0, 58.0, 76.0], [5.1, 4.5, 6.0, 5.3, 5.5]]


## Adding Elements to an array

###### Append new elements at the end of an array

In [11]:
score=np.append(score,90)
print(score)
score=np.append(score,[45,59,94])
print(score)

[70 63 81 58 76 90]
[70 63 81 58 76 90 45 59 94]


###### Insert new element(s) at a specific position in an array

In [12]:
score=np.insert(score,3,20)
print(score)

[70 63 81 20 58 76 90 45 59 94]


## Removing Elements from an array

###### Delete row on index 2 from an array

In [13]:
score=np.delete(score,2,axis=0)
print(score)

[70 63 20 58 76 90 45 59 94]


###### Delete column on index 2 from an array

In [14]:
# score=np.delete(score,2,axis=1)
# print(score)

## NumPy Statistics functions

###### Find the length of 1-Dimensional numpy array

In [15]:
len(score)

9

###### Sum all elements in 1-Dimensional array using sum() function
sum() function offers better performance than manually iterating through each element

In [16]:
# three different ways to sum 1-D arrays
print(np.sum(score,axis=0))
print(score.sum(axis=0))

575
575


###### Find max element in a 1-Dimensional numpy array

In [17]:
print(np.max(score,axis=0))
print(score.max(axis=0))

94
94


###### Find min element in a 1-Dimensional numpy array

In [18]:
print(np.min(score,axis=0))
print(score.min(axis=0))

20
20


###### Find mean of a 1-Dimensional numpy array

In [19]:
print(np.mean(score,axis=0))
print(score.mean(axis=0))

63.888888888888886
63.888888888888886


###### Find variance of a 1-Dimensional numpy array

In [20]:
print(np.var(score,axis=0))
print(score.var(axis=0))

457.2098765432099
457.2098765432099


###### Find standard deviation of a 1-Dimensional numpy array 

In [21]:
print(np.std(score,axis=0))
print(score.std(axis=0))

21.3824665682706
21.3824665682706


###### Find correlation coefficient  of a 1-Dimensional numpy array 

In [22]:
print(np.corrcoef(score))

1.0


## Read Data to NumPy

###### Read data from text file

In [23]:
students_data=np.loadtxt('students.txt')
print(students_data)

[[78.   5.1]
 [56.   4.5]
 [67.   5.3]
 [73.   6. ]]


###### Read data from csv file

In [24]:
titanic_data=np.genfromtxt('titanic.csv',delimiter=',')
print(titanic_data)

[[    nan     nan     nan ...     nan     nan     nan]
 [ 0.      3.         nan ...  1.      0.      7.25  ]
 [ 1.      1.         nan ...  1.      0.     71.2833]
 ...
 [ 0.      3.         nan ...  1.      2.     23.45  ]
 [ 1.      1.         nan ...  0.      0.     30.    ]
 [ 0.      3.         nan ...  0.      0.      7.75  ]]


## Store Data to File

###### Save data to a text file

In [25]:
np.savetxt('students_saved_array.txt',students_data,delimiter=' ')

###### Save data to a csv file

In [26]:
np.savetxt('titanic_saved_array.csv',titanic_data,delimiter=',')